export default {
	frança:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%29.svg/540px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%29.svg.png',
	espanya:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/540px-Flag_of_Spain.svg.png',
	alemanya:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/600px-Flag_of_Germany.svg.png',
	itàlia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/540px-Flag_of_Italy.svg.png',
	portugal:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/540px-Flag_of_Portugal.svg.png',
	grècia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/540px-Flag_of_Greece.svg.png',
	'estats units':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/540px-Flag_of_the_United_States.svg.png',
	austràlia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/540px-Flag_of_Australia_%28converted%29.svg.png',
	argentina:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/540px-Flag_of_Argentina.svg.png',
	xile: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/540px-Flag_of_Chile.svg.png',
	'sud-àfrica':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/540px-Flag_of_South_Africa.svg.png',
	'nova zelanda':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/540px-Flag_of_New_Zealand.svg.png',
	àustria:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/540px-Flag_of_Austria.svg.png',
	hongria:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/540px-Flag_of_Hungary.svg.png',
	brasil:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/540px-Flag_of_Brazil.svg.png',
	romania:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/540px-Flag_of_Romania.svg.png',
	israel:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/300px-Flag_of_Israel.svg.png',
	canadà:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/540px-Flag_of_Canada_%28Pantone%29.svg.png',
	suïssa:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/540px-Flag_of_Switzerland.svg.png',
	xina: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/540px-Flag_of_the_People%27s_Republic_of_China.svg.png',
	xèquia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/540px-Flag_of_the_Czech_Republic.svg.png',
	afganistan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/540px-Flag_of_Afghanistan.svg.png',
	albània:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/540px-Flag_of_Albania.svg.png',
	algeria:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/540px-Flag_of_Algeria.svg.png',
	andorra:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/540px-Flag_of_Andorra.svg.png',
	angola:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/540px-Flag_of_Angola.svg.png',
	'antigua i barbuda':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/540px-Flag_of_Antigua_and_Barbuda.svg.png',
	armènia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/540px-Flag_of_Armenia.svg.png',
	bahames:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/540px-Flag_of_the_Bahamas.svg.png',
	bahrain:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/540px-Flag_of_Bahrain.svg.png',
	bangladesh:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/540px-Flag_of_Bangladesh.svg.png',
	barbados:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/540px-Flag_of_Barbados.svg.png',
	bielorússia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/540px-Flag_of_Belarus.svg.png',
	bèlgica:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/540px-Flag_of_Belgium.svg.png',
	benín:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/540px-Flag_of_Benin.svg.png',
	bolívia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/540px-Flag_of_Bolivia.svg.png',
	bòsnia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/540px-Flag_of_Bosnia_and_Herzegovina.svg.png',
	botswana:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/540px-Flag_of_Botswana.svg.png',
	brunei:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/540px-Flag_of_Brunei.svg.png',
	bulgària:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/540px-Flag_of_Bulgaria.svg.png',
	burkina:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/540px-Flag_of_Burkina_Faso.svg.png',
	burundi:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/540px-Flag_of_Burundi.svg.png',
	cambodja:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/540px-Flag_of_Cambodia.svg.png',
	camerun:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/540px-Flag_of_Cameroon.svg.png',
	capverd:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/540px-Flag_of_Cape_Verde.svg.png',
	centreafricana:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/540px-Flag_of_the_Central_African_Republic.svg.png',
	chad: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/540px-Flag_of_Chad.svg.png',
	comores:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/540px-Flag_of_the_Comoros.svg.png',
	congo:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/540px-Flag_of_the_Republic_of_the_Congo.svg.png',
	'costa marfil':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_C%C3%B4te_d%27Ivoire.svg/540px-Flag_of_C%C3%B4te_d%27Ivoire.svg.png',
	croàcia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/540px-Flag_of_Croatia.svg.png',
	cuba: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/540px-Flag_of_Cuba.svg.png',
	dinamarca:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/540px-Flag_of_Denmark.svg.png',
	djibouti:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/540px-Flag_of_Djibouti.svg.png',
	dominica:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/540px-Flag_of_Dominica.svg.png',
	ecuador:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/540px-Flag_of_Ecuador.svg.png',
	egipte:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/540px-Flag_of_Egypt.svg.png',
	'el salvador':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/540px-Flag_of_El_Salvador.svg.png',
	equatorial:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/540px-Flag_of_Equatorial_Guinea.svg.png',
	eslovàquia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/540px-Flag_of_Slovakia.svg.png',
	eslovènia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/540px-Flag_of_Slovenia.svg.png',
	estònia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/540px-Flag_of_Estonia.svg.png',
	etiòpia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/540px-Flag_of_Ethiopia.svg.png',
	fiji: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/540px-Flag_of_Fiji.svg.png',
	finlàndia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/540px-Flag_of_Finland.svg.png',
	gàmbia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/540px-Flag_of_The_Gambia.svg.png',
	geòrgia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/540px-Flag_of_Georgia.svg.png',
	granada:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/540px-Flag_of_Grenada.svg.png',
	guatemala:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/540px-Flag_of_Guatemala.svg.png',
	guinea:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/540px-Flag_of_Guinea.svg.png',
	'guinea ecuatorial':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/540px-Flag_of_Equatorial_Guinea.svg.png',
	'guinea bissau':
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/540px-Flag_of_Guinea-Bissau.svg.png',
	guyana:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/540px-Flag_of_Guyana.svg.png',
	haití:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/540px-Flag_of_Haiti.svg.png',
	honduras:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/540px-Flag_of_Honduras.svg.png',
	icelanda:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/540px-Flag_of_Iceland.svg.png',
	india:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/540px-Flag_of_India.svg.png',
	indonèsia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/540px-Flag_of_Indonesia.svg.png',
	iran: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/540px-Flag_of_Iran.svg.png',
	iraq: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/540px-Flag_of_Iraq.svg.png',
	irlanda:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/540px-Flag_of_Ireland.svg.png',
	jamaica:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/540px-Flag_of_Jamaica.svg.png',
	japó: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/540px-Flag_of_Japan.svg.png',
	jordània:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/540px-Flag_of_Jordan.svg.png',
	kazakhstan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/540px-Flag_of_Kazakhstan.svg.png',
	kenya:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/540px-Flag_of_Kenya.svg.png',
	kirguizistan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/540px-Flag_of_Kyrgyzstan.svg.png',
	kuwait:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/540px-Flag_of_Kuwait.svg.png',
	laos: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/540px-Flag_of_Laos.svg.png',
	lesotho:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/540px-Flag_of_Lesotho.svg.png',
	letònia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/540px-Flag_of_Latvia.svg.png',
	liban:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/540px-Flag_of_Lebanon.svg.png',
	libèria:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/540px-Flag_of_Liberia.svg.png',
	líbia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/540px-Flag_of_Libya.svg.png',
	lituània:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/540px-Flag_of_Lithuania.svg.png',
	luxemburg:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/540px-Flag_of_Luxembourg.svg.png',
	madagascar:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/540px-Flag_of_Madagascar.svg.png',
	malàsia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/540px-Flag_of_Malaysia.svg.png',
	malawi:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/540px-Flag_of_Malawi.svg.png',
	maldives:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/540px-Flag_of_Maldives.svg.png',
	mali: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/540px-Flag_of_Mali.svg.png',
	malta:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/540px-Flag_of_Malta.svg.png',
	marroc:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/540px-Flag_of_Morocco.svg.png',
	maurici:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/540px-Flag_of_Mauritius.svg.png',
	mauritània:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/540px-Flag_of_Mauritania.svg.png',
	mèxic:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/540px-Flag_of_Mexico.svg.png',
	mònaco:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/540px-Flag_of_Monaco.svg.png',
	mongòlia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/540px-Flag_of_Mongolia.svg.png',
	montenegro:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/540px-Flag_of_Montenegro.svg.png',
	mozambic:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/540px-Flag_of_Mozambique.svg.png',
	namíbia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/540px-Flag_of_Namibia.svg.png',
	nepal:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/540px-Flag_of_Nepal.svg.png',
	nicaragua:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/540px-Flag_of_Nicaragua.svg.png',
	níger:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/540px-Flag_of_Niger.svg.png',
	nigèria:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/540px-Flag_of_Nigeria.svg.png',
	noruega:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/540px-Flag_of_Norway.svg.png',
	nova: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/540px-Flag_of_New_Zealand.svg.png',
	oman: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/540px-Flag_of_Oman.svg.png',
	pakistan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/540px-Flag_of_Pakistan.svg.png',
	palau:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/540px-Flag_of_Palau.svg.png',
	palestina:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Flag_of_Palestine_%28original_version%29.svg/300px-Flag_of_Palestine_%28original_version%29.svg.png',
	panamà:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/540px-Flag_of_Panama.svg.png',
	papua:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/540px-Flag_of_Papua_New_Guinea.svg.png',
	paraguai:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/540px-Flag_of_Paraguay.svg.png',
	perú: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/540px-Flag_of_Peru.svg.png',
	polònia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/540px-Flag_of_Poland.svg.png',
	qatar:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/540px-Flag_of_Qatar.svg.png',
	regne:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_the_United_Kingdom.svg/540px-Flag_of_the_United_Kingdom.svg.png',
	ruanda:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/540px-Flag_of_Rwanda.svg.png',
	rússia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/540px-Flag_of_Russia.svg.png',
	samoa:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/540px-Flag_of_Samoa.svg.png',
	sant: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Saint_Kitts_and_Nevis.svg/540px-Flag_of_Saint_Kitts_and_Nevis.svg.png',
	santa:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Lucia.svg/540px-Flag_of_Saint_Lucia.svg.png',
	san: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Vincent_and_the_Grenadines.svg/540px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png',
	senegal:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/540px-Flag_of_Senegal.svg.png',
	seychelles:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/540px-Flag_of_Seychelles.svg.png',
	sierra:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/540px-Flag_of_Sierra_Leone.svg.png',
	singapur:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/540px-Flag_of_Singapore.svg.png',
	síria:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/540px-Flag_of_Syria.svg.png',
	somàlia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/540px-Flag_of_Somalia.svg.png',
	sri: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/540px-Flag_of_Sri_Lanka.svg.png',
	sudan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/540px-Flag_of_Sudan.svg.png',
	suècia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/540px-Flag_of_Sweden.svg.png',
	suíssa:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/540px-Flag_of_Switzerland.svg.png',
	tadjikistan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/540px-Flag_of_Tajikistan.svg.png',
	tanzània:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/540px-Flag_of_Tanzania.svg.png',
	timor:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/540px-Flag_of_East_Timor.svg.png',
	togo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/540px-Flag_of_Togo.svg.png',
	tonga:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/540px-Flag_of_Tonga.svg.png',
	tunísia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/540px-Flag_of_Tunisia.svg.png',
	turkmenistan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/540px-Flag_of_Turkmenistan.svg.png',
	turquia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/540px-Flag_of_Turkey.svg.png',
	tuvalu:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/540px-Flag_of_Tuvalu.svg.png',
	ucraïna:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/540px-Flag_of_Ukraine.svg.png',
	uganda:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/540px-Flag_of_Uganda.svg.png',
	uruguai:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/540px-Flag_of_Uruguay.svg.png',
	uzbekistan:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/540px-Flag_of_Uzbekistan.svg.png',
	vanuatu:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/540px-Flag_of_Vanuatu.svg.png',
	veneçuela:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/540px-Flag_of_Venezuela.svg.png',
	vietnam:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/540px-Flag_of_Vietnam.svg.png',
	zàmbia:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/540px-Flag_of_Zambia.svg.png',
	filipines:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/540px-Flag_of_the_Philippines.svg.png',
	zimbabwe:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/540px-Flag_of_Zimbabwe.svg.png',
	catalunya:
		'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Catalonia.svg/1280px-Flag_of_Catalonia.svg.png'
};
